### ISSUE TITLE
matchpeaks.pl unable to request sufficient memory

### ISSUE THREAD

**Issue by jpsmith5** [eblancoga/seqcode#2]
When attempting to run even the `test_matchpeaks.pl` script, `matchpeaks` is unable to request sufficient memory (even when run on a server with 1000GB of available RAM: 
```
grep MemTotal /proc/meminfo
MemTotal:       1056755972 kB
```

Example output from the test (the `test_1A_test_1B_matchpeaks` file):
```


			***** Running matchpeaks (SeqCode_v1.0) by Enrique Blanco (2020) *****
			***** GitHub  source code: https://github.com/eblancoga/seqcode   *****
			***** SeqCode homepage at: http://ldicrocelab.crg.es             *****


> 0. Running on Fri Feb  4 15:54:00 2022
> 1. Request Memory to Operating System
ERROR
	Not enough memory: Peaks matrix (MAXPEAKS)
SEE ALSO
	SeqCode homepage: http://ldicrocelab.crg.es
	GitHub source code: https://github.com/eblancoga/seqcode

AUTHORS
	Written by Enrique Blanco

SeqCode_v1.0						User commands						SeqCode_v1.0

	__________________________________________________________________________

	Memory usage: 	0.00 Megabytes
	CPU time: 	0.00 secs
	Total time: 	0 secs (0.00 mins)

```

Any suggestions or thoughts for where this issue is stemming from?

**Comment by eblancoga** [comment]
Hi Jason,

Sure, the reason for this is that the software makes an initial reservation of memory relying on the expected number of BED records per chromosome in the input files and by default this value is set very high to deal with a massive amount of peaks (which is not always the case)

Please, follow these steps to adapt seqcode binaries to your setup:

(1) open the header file of seqcode (use emacs or any other text editor)
emacs include/seqcode/seqcode.h 

(2) search for this definition

/* Max number of peaks/chr                  */
#define MAXPEAKS 500000

(3) decrease the value for instance to a more realistic limit (the test example contains 2200 peaks in total inside the biggest BED file)

#define MAXPEAKS 10000

(4) clean the binaries
make clean

(5) compile again and repeat the test afterwards
make all

Best!

**Comment by jpsmith5** [comment]
Hey @eblancoga,

Still getting the same error. Changed MAXPEAKS to 10000. Cleaned and recompiled.

The test output:
```
./tests/test_matchpeaks.pl -v
%%%% Starting SeqCode test for the matchpeaks tool by Enrique Blanco (Sat Feb  5 10:18:27 EST 2022)

%%%% Stage 0.  Reading options  [DONE]

%%%% Stage 1.  Running the test for H3K4me3-H3K27me3 overlap in mESC (H3K4me3+H3K27me3 peaks, chr10)
%%%% bin/matchpeaks -v tests/inputs/H3K4me3_chr10.bed tests/inputs/H3K27me3_chr10.bed test_1A test_1B 2> mystderr.txt
mv: cannot stat ‘test_1A_test_1B_matchpeaks’: No such file or directory
        [DONE]

%%%% Stage 2.  Running the test for H3K4me3-H3K27me3 overlap in mESC (H3K4me3+H3K27me3 peaks, chr10, overlap (at least) = 1000 bp)
%%%% bin/matchpeaks -v -l 1000 tests/inputs/H3K4me3_chr10.bed tests/inputs/H3K27me3_chr10.bed test_2A test_2B 2> mystderr.txt
mv: cannot stat ‘test_2A_test_2B_matchpeaks’: No such file or directory
        [DONE]

%%%% Stage 3.  Finishing the test (matchpeaks)
%%%% Checking output dir 1: tests/outputs/matchpeaks/test_1A_test_1B_matchpeaks [OK]
%%%% Checking output dir 2: tests/outputs/matchpeaks/test_2A_test_2B_matchpeaks [OK]
%%%% Total running time (hours): 0  hours
%%%% Total running time (minutes): 0  mins
%%%% Total running time (seconds): 0  secs
%%%% Successful termination:    [DONE]
```
Not sure why it's not seeing the file to `mv`, as it is there, because if I look at the `outputs/matchpeaks/test_2A_test_2B_matchpeaks` file:
```


			***** Running matchpeaks (SeqCode_v1.0) by Enrique Blanco (2020) *****
			***** GitHub  source code: https://github.com/eblancoga/seqcode   *****
			***** SeqCode homepage at: http://ldicrocelab.crg.es             *****


> 0. Running on Sat Feb  5 10:18:27 2022
> 1. Request Memory to Operating System
ERROR
	Not enough memory: Peaks matrix (MAXPEAKS)
SEE ALSO
	SeqCode homepage: http://ldicrocelab.crg.es
	GitHub source code: https://github.com/eblancoga/seqcode

AUTHORS
	Written by Enrique Blanco

SeqCode_v1.0						User commands						SeqCode_v1.0

	__________________________________________________________________________

	Memory usage: 	0.00 Megabytes
	CPU time: 	0.00 secs
	Total time: 	0 secs (0.00 mins)
```

I still get the memory failure. Any additional thoughts?

**Comment by eblancoga** [comment]
Hello Jason!

You're doing well. This value of MAXPEAKS is the max value per chr so, for example, for 20 chromosomes, MAXPEAKS=10000 would mean in the "worst" case 200,000 peaks genome-wide, which it is still a lot for a ChIPseq. To sum up, I would suggest you to decrease the value up to 1000 and test again. It is an extremely low value, but at least, we would see whether the issue is here or not. The test example contains less than 3000 peaks in one BED file and about 800 peaks in the other (for the whole genome) so that it should work with MAXPEAKS=1000 in every computer, even with low amounts of available RAM memory.
Thanks for the feedback, BTW!

**Comment by jpsmith5** [comment]
That seemed to take care of it. Will close for now unless it comes up again. Thank you for your help!
