### ISSUE TITLE
ReadPeaksFile.c Segmentation Fault Error

### ISSUE THREAD

**Issue by pql9132** [eblancoga/seqcode#3]
When running "matchpeaks" on BED files, a segmentation fault occurred in the "ReadPeaksFile.c" code without any further error message. It seems that the cause was that the "MAXCHRS" macro was too low to account for all the unique chromosome names in the BED file. Increasing this value and recompiling solved the issue. As the code already checks if the chromosome key is new, adding a count of unique chromosomes in each BED file when reading, and checking to see if the max is exceeded to produce an error message would make identifying this issue and its solution easier.

**Comment by eblancoga** [comment]
Indeed, it was necessary to add a control over the number of chromosome names when reading BED records.
Following tightly your suggestion, I added such a control in the ReadPeaksFile.c. Additionally, I added a similar control
when working with BAM files for metaplots, signal strenght, etc. in the moment in which the UCSC chromosome information
file (chromosome, chromosome size) is loaded by SeqCode. Finally, to avoid big memory requirements by default, I reduced
MAXCHRS to 50 (from 500) and when the user (as in your former case) works with more distinct chromosome names, he/she will receive the warning message informing to increase MAXCHRS in the include file (as you did).
Thanks a lot for the feedback!
